/**
 * The full curated Lucide set (§6.5). Canonical lucide 1.51.0 names only, never aliases (for example
 * `circle-question-mark`, not `circle-help`). Keys are the kebab-case file names; values are the PascalCase
 * IconNode exports. A component that needs another icon adds it here, so the bundle carries only listed icons.
 */
import {
  BatteryCharging,
  BedDouble,
  BellOff,
  Blinds,
  CalendarDays,
  Camera,
  CameraOff,
  Car,
  Check,
  CircleAlert,
  CircleCheck,
  CircleQuestionMark,
  Clock,
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning,
  CloudMoon,
  CloudRain,
  CloudRainWind,
  CloudSnow,
  CloudSun,
  Cloudy,
  CookingPot,
  DoorClosed,
  DoorOpen,
  Droplets,
  EyeOff,
  Fan,
  Flame,
  House,
  Info,
  Leaf,
  Lightbulb,
  LightbulbOff,
  Lock,
  Menu,
  Microwave,
  Minus,
  Moon,
  Music,
  Pause,
  Play,
  Plug,
  PlugZap,
  Plus,
  Power,
  Refrigerator,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  Shirt,
  SkipBack,
  SkipForward,
  Snowflake,
  Speaker,
  Sun,
  Sunrise,
  Sunset,
  Thermometer,
  Timer,
  Tornado,
  TriangleAlert,
  Tv,
  Unplug,
  Utensils,
  Video,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  WashingMachine,
  Wifi,
  WifiOff,
  Wind,
  X,
  Zap,
} from 'lucide';
import type { IconNode } from 'lucide';

// Grouped by the first §6.5 area that uses each icon; an icon shared by several areas is listed once.
export const ICONS = Object.freeze({
  // Shell and header
  shield: Shield,
  'shield-check': ShieldCheck,
  'shield-alert': ShieldAlert,
  'shield-off': ShieldOff,
  menu: Menu,
  x: X,
  check: Check,
  info: Info,
  wifi: Wifi,
  'wifi-off': WifiOff,
  house: House,
  'circle-question-mark': CircleQuestionMark,
  'circle-alert': CircleAlert,
  'triangle-alert': TriangleAlert,
  // Today
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  cloudy: Cloudy,
  'cloud-sun': CloudSun,
  'cloud-moon': CloudMoon,
  'cloud-rain': CloudRain,
  'cloud-drizzle': CloudDrizzle,
  'cloud-rain-wind': CloudRainWind,
  'cloud-snow': CloudSnow,
  'cloud-hail': CloudHail,
  'cloud-lightning': CloudLightning,
  'cloud-fog': CloudFog,
  wind: Wind,
  tornado: Tornado,
  snowflake: Snowflake,
  droplets: Droplets,
  thermometer: Thermometer,
  sunrise: Sunrise,
  sunset: Sunset,
  // Comfort
  flame: Flame,
  fan: Fan,
  power: Power,
  'bed-double': BedDouble,
  minus: Minus,
  plus: Plus,
  leaf: Leaf,
  // Home
  lightbulb: Lightbulb,
  'lightbulb-off': LightbulbOff,
  blinds: Blinds,
  play: Play,
  pause: Pause,
  'washing-machine': WashingMachine,
  // Appliance kinds read from the household's own appliance names (model/home.ts applianceIcon); plug is the
  // neutral glyph for any other appliance.
  utensils: Utensils,
  shirt: Shirt,
  'cooking-pot': CookingPot,
  microwave: Microwave,
  refrigerator: Refrigerator,
  timer: Timer,
  speaker: Speaker,
  plug: Plug,
  unplug: Unplug,
  // Cameras
  camera: Camera,
  'camera-off': CameraOff,
  video: Video,
  'eye-off': EyeOff,
  lock: Lock,
  // Garage and car
  car: Car,
  zap: Zap,
  'plug-zap': PlugZap,
  'battery-charging': BatteryCharging,
  // Media
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  volume: Volume,
  'volume-1': Volume1,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  tv: Tv,
  music: Music,
  // Upcoming
  'calendar-days': CalendarDays,
  clock: Clock,
  // Security and health
  'bell-off': BellOff,
  'door-open': DoorOpen,
  'door-closed': DoorClosed,
  'circle-check': CircleCheck,
}) satisfies Readonly<Record<string, IconNode>>;
