id: neo_everyone_up
alias: Everyone Up - Sleep Mode Off
description: When both Pranav and Abhinaya leave the bed, turn off sleep mode
triggers:
- entity_id:
  - binary_sensor.abhinaya_s_eight_sleep_side_bed_presence
  to: 'off'
  for:
    minutes: 2
  trigger: state
- entity_id:
  - binary_sensor.pranav_s_eight_sleep_side_bed_presence
  to: 'off'
  for:
    minutes: 2
  trigger: state
conditions:
- condition: state
  entity_id: binary_sensor.abhinaya_s_eight_sleep_side_bed_presence
  state: 'off'
- condition: state
  entity_id: binary_sensor.pranav_s_eight_sleep_side_bed_presence
  state: 'off'
actions:
- action: climate.turn_off
  target:
    entity_id:
    - climate.pranav_s_eight_sleep_side_climate
    - climate.abhinaya_s_eight_sleep_side_climate
- action: media_player.turn_off
  target:
    entity_id: media_player.wigglytuff_base_speaker
- action: notify.mobile_app_pranavs_pocket_tv
  data:
    title: ☀️ Good Morning!
    message: Everyone's up — Eight Sleep and white noise turned off
mode: single
