id: neo_low_range_reminder
alias: Tesla Low Range Bedtime Reminder
description: Remind to plug in Tesla if range < 100mi when going to bed
triggers:
- trigger: time
  at: '20:00:00'
conditions:
- condition: numeric_state
  entity_id: sensor.killua_battery_range
  below: 100
- condition: state
  entity_id: binary_sensor.killua_charge_cable
  state: 'off'
actions:
- action: notify.mobile_app_pranavs_pocket_tv
  metadata: {}
  data:
    message: Tesla is at {{ states('sensor.killua_battery_range') | round(0) }} mi range and not plugged in
    data:
      priority: high
      ttl: 0
    title: 🔋 Plug in Killua!
- action: notify.mobile_app_iphone_14_pro
  metadata: {}
  data:
    message: Tesla is at {{ states('sensor.killua_battery_range') | round(0) }} mi range and not plugged in
    data:
      priority: high
      ttl: 0
    title: 🔋 Plug in Killua!
mode: single
